<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>UsageTracker.Cli</RootNamespace>
    <AssemblyName>UsageTracker.Cli</AssemblyName>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UsageTracker.Core\UsageTracker.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
